service: holibot

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:
  handler:
    handler: handler.handler
    description: The handler for holibot. Invoked by Lex when users chat to Holibot.

    environment:
      TimeTasticToken: ${file(./token.yml):timetastic}
      TimeTasticEndpoint: https://app.timetastic.co.uk/api/
      SlackToken: ${file(./token.yml):slack}

    package:
      include:
        - timetastic.js
        - slack.js
        - formatters.js